apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::593300579669:role/eksctl-roboshop-1-cluster-ServiceRole-f6flFf1UZ8Yn
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::160885265516:user/suresh
      username: suresh
      groups:
        - system:masters
