apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::593300579669:role/eksctl-roboshop-1-nodegroup-spot-NodeInstanceRole-uBaAdKX08NfJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::593300579669:user/Suresh
      username: Suresh
metadata:
  creationTimestamp: "2026-04-17T11:48:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1214"
  uid: 6e1aed63-9800-42f3-ad27-1389fcb6d337
