apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::593300579669:role/eksctl-roboshop-1-addon-iamserviceaccount-rob-Role1-d8M28NixJZv9
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop